version: 2.1
orbs:
  extensions: solidusio/extensions@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

commands:
  create-dummy-extension:
    steps:
      - run:
          name: Create dummy extension
          command: bin/create-dummy-extension

jobs:
  test-run-with-postgres:
    executor: extensions/postgres
    steps:
      - checkout
      - run:
          bundle install
      - create-dummy-extension
      - run:
          cd solidus_dummy_extension
      - extensions/run-tests-solidus-older
      - extensions/store-test-results
  test-run-with-mysql:
    executor: extensions/mysql
    steps:
      - checkout
      - run:
          bundle install
      - create-dummy-extension
      - run:
          cd solidus_dummy_extension
      - extensions/run-tests-solidus-current
      - extensions/store-test-results
  test-run-with-sqlite:
    executor: extensions/sqlite
    steps:
      - checkout
      - run:
          bundle install
      - create-dummy-extension
      - run:
          cd solidus_dummy_extension
      - extensions/run-tests-solidus-master
      - extensions/store-test-results

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - test-run-with-postgres:
          filters: *filters
      - test-run-with-mysql:
          filters: *filters
      - test-run-with-sqlite:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: solidusio/extensions
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - test-run-with-postgres
            - test-run-with-mysql
            - test-run-with-sqlite
          enable-pr-comment: false
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
